pkg:
  user: octohub
  language: dummy
  project: "octoflow"
  binary: "-"
  service: "-"
  lang_opts:
  env:
  submodules:
    - name: "Octoflow Bot"
      path: "bot"
    - name: "Octoflow Webserver/API"
      path: "webserver"
